# --------------------------------------------------------
# some useful extensions to have
vscode:
  extensions:
    - eamodio.gitlens
    - njpwerner.autodocstring
    - lextudio.restructuredtext
    - ritwickdey.liveserver
    - ms-python.python
    - yzhang.markdown-all-in-one
    - bungcip.better-toml
    - mhutchie.git-graph
